language: python
python:
  - "2.7"
  - "3.7"
cache: pip

env:
  - TOXENV=py27
  - TOXENV=py3
  - TOXENV=lint

install:
  - pip install -U pip
  - pip install -U tox
  - pip --version
  - tox --version

script:
  - tox

deploy:
  - provider: pypi
    repo: greg-hellings/dnszone
    user: "${PYPI_USER}"
    password: "${PYPI_PASSWORD}"
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      condition: $TOXENV = py3
