language: python
versions:
  - "2.7"
  - "3.7"
cache: pip

env:
  - TOXENV=py27
  - TOXENV=py3
  - TOXENV=lint

install:
  - pip install -U pip
  - pip install -U tox
  - pip --version
  - tox --version

script:
  - tox
